name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        default: "dev"
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  deploy:
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with docker compose
        run: docker compose up -d --build
