name: Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        default: "dev"
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build & and push to Docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/vue-tracker-app:${{ github.ref_name }}
            ${{ vars.DOCKER_HUB_USERNAME }}/vue-tracker-app:${{ github.sha }}
      - name: Push docker container to registry
        run: echo "Pushing the container to registry"
