name: Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging      
