# API keys, credentials, and other secrets should never be committed to your repository. This workflow uses the GitHub Secret Scanning API to scan for secrets in your codebase and alert you if any are found.
name: Secrets Scan
on:
  workflow_call:
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate scanning

      - name: Run GitLeaks Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
